### ISSUE TITLE
Psychotherapy Research

### ISSUE THREAD

**Issue by AnthonySMyers** [nnguyen682/CECS491ATeam4#36]
Review research documents that cover different approaches to psychotherapy. Determine what advice would be appropriate to give within the scope of the application.

**Comment by nnguyen682** [comment]
I have looked up Psychothrapy  from psychiatry website. And I learned that 75 percent of people who try the Psychothrapy get some positive effects from it. I include where is the percent coming below. 


American Psychological Association. Understanding psychotherapy and how it works. 2016. http://www.apa.org/helpcenter/understanding-psychotherapy.aspx
