### ISSUE TITLE
Read Device Address API Guidelines

### ISSUE THREAD

**Issue by AnthonySMyers** [nnguyen682/CECS491ATeam4#38]
This is provided through AWS. The guidelines cover agreements that AWS coders must make to use device address API services.

**Comment by nnguyen682** [comment]
We have to ask the user permission to access their device address information. Accessing their address without asking is defined as illegal.

**Comment by AnthonySMyers** [comment]
I have written a text document that summarizes the main points in the Device Address API guidelines that Amazon has provided for us.

[Device Address API.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a66619da7ba990013f053dc/125516c66e82c728ace21e0d46cc918c2a8186e9aeedbb51a14ee3d408760e316546b3397f8fe62bab0021435a0e48fd100c0d12fea8812ba6e73c708d0a59edd4390b72d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e0888f47381b0d1f88fd4f78.txt)

**Comment by AnthonySMyers** [comment]
We will favor suggestions that would work within the context of our project. This may include therapist locations or clinics that specialize in depression therapy. This will only be used to further enhance the functionality of Good Vibes and would be optional based on the consent of the user.
