### ISSUE TITLE
Test Results + DynamoDB

### ISSUE THREAD

**Issue by AnthonySMyers** [nnguyen682/CECS491ATeam4#40]
User test results will be stored in our DynamoDB Table. These user values will be referenced for feature enhancements regarding more specific response results that cater to the user between user sessions.

**Comment by AnthonySMyers** [comment]
Good Vibes now has a table attribute called 'Score' that will be written to a DynamoDB table whenever a user finishes an assessment test. If a user has already taken the test, the 'Score' attribute will be referenced and Good Vibes will inform the user of previous test scores. Good Vibes may also reference the 'Score' attribute to offer advice that would be more well-suited for  the user's current conditions. The 'Score' attribute will only hold scores based on depression severity. We are trying to expand the number of attributes in the DynamoDB table to keep track of more user information regarding the user's state of depression. This may include user background assessment for determining sources of stress. Psychotherapy studies say that identifying and facing underlying sources of stress can help patients cope with depression. Sources of stress may include childhood trauma, lack of social communication, overbearing workloads, lack of sleep, or the loss of a loved one.

**Comment by nnguyen682** [comment]
There are some errors in our codes where we set the skill state to null after we emit alexa to say something so the process reach the load the line of code that set the skill state to null
