### ISSUE TITLE
In-Class User Testing

### ISSUE THREAD

**Issue by jespinoza17** [nnguyen682/CECS491ATeam4#49]
https://docs.google.com/document/d/1LU9uKrTX46bWpD566QVhOncmROx9y6Qmg46YtRRQjyU/edit

**Comment by jespinoza17** [comment]
We received great feedback from two other teams that we summarized in about two pages. We will submit our reflection on user test session 1 when all members finish their reflections/insights from the feedback.

**Comment by AnthonySMyers** [comment]
Group Eco Pal gave us useful feedback regarding the discussion feature. We will still have open-ended and restricted questions, but may get rid of conversation ending statements. We will still start the conversation with the "How has your day been?", but have the first few layers beyond that be purely open-ended questions. Once we have hit the third layer of conversation Good Vibes will randomly select between open-ended and restricted questions.

**Comment by AnthonySMyers** [comment]
This design choice was made, because we want the discussion feature to allow the user to open up and tell Good Vibes as much information as possible. In return Good Vibes will determine responses that relate to statements from previously held conversations.

**Comment by AnthonySMyers** [comment]
Group Let's Talk gave us advice regarding the scope of the project. They said that we would be better off if we re-purposed the project to focus on something other than an anti-depression application. They stated that the liability for proposing the application as any form of "alternative medicine" would be dangerous for us as developers.
