### ISSUE TITLE
Discussion Tree

### ISSUE THREAD

**Issue by AnthonySMyers** [nnguyen682/CECS491ATeam4#51]
This diagram is to map out the enhancements for the discussion feature for Good Vibes. We are planning on implementing a limited tier system for dialogue options, because continuous dialogue streams can span a virtually infinite amount of options.

**Comment by AnthonySMyers** [comment]
Link to the draw.io diagram: 


https://www.draw.io/#G1UuFm-0lD6LTEOcg3NDKDNZT_qghgRV01

**Comment by AnthonySMyers** [comment]
Some dialogues will cut the tree short, to give the illusion that they are working in a dynamic/natural way. The main idea will be to populate the tree with slight variations of semantically identical statements with lexical variations. We can achieve this idea using slots to our advantage.

**Comment by AnthonySMyers** [comment]
It would also be ideal to have the ability to reference user statements that were made during the discussion event. This can be accomplished through the use of slots, but expanded on with the DynamoDB table. The DynamoDB table will allow us to reference user statements across sessions, which will make the application even more dynamic for the user.

**Comment by nnguyen682** [comment]
I add some texts and more boxes that has similar meaning  to the diagram and also change the color and style of the user boxes. Gathering more ideas and update this later

**Comment by AnthonySMyers** [comment]
Responses from Alexa in the discussion feature will be handled under three categories:

1.)  A response can lead to the end of a discussion tree.

2.)  A response can be a restricted question, meaning that it will have few answers that are accepted from the user. An example of this would be a binary user response such as a 'yes' or 'no'. 

3.) A response can be an open-ended question, meaning that the user can respond in any way they want. We are hoping to implement trigger words for these types of questions such as 'watched a movie' or 'did good on a test' that will lead to a more specific response. If a trigger word is not detected, then Alexa would respond to the user with a general 'that sounds like fun' type of response.
