### ISSUE TITLE
Email To professor Google Docs - Weekly Progress

### ISSUE THREAD

**Issue by nnguyen682** [nnguyen682/CECS491ATeam4#53]
Everyone Adds their pieces about the process that we make over the week. I sent everyone an email but below is the link connecting straight to it
https://docs.google.com/document/d/1zsQaG_SfFNulenFqgF0sFfJG1SAqE86kw21kpu_kxj0/edit

**Comment by AnthonySMyers** [comment]
This email was sent to the professor while she was in Europe for a conference. It describes the progress we had made throughout the week.
