### ISSUE TITLE
Run Successfully A Mock Demo

### ISSUE THREAD

**Issue by nnguyen682** [nnguyen682/CECS491ATeam4#54]
The demo consists of basic functions: store name, start discussion, take assessment test, and get advice.

**Comment by nnguyen682** [comment]
Add an intention named clearName to clear the information that is stored in databased under the name of userName, storing the username, and story, storing the type of new and old story.

**Comment by AnthonySMyers** [comment]
The demo will focus on the front-end aspect of Good Vibes. The user does not have to be aware of the background tasks that the Lambda Function and DynamoDB table handle. However, feedback regarding front-end conflicts will mean that mechanics will have to be updated within the back-end.

**Comment by AnthonySMyers** [comment]
Goals for Demo:
1.) Username is requested, stored, and referenced properly
2.) User discussion state is stored for future reference on Good Vibes startup
3.) User assessment test runs, calculates, and designates a rating
4.) Advice gives general advice (for now)
5.) Discussion asks about day (for now)

Future Goals:
1.) Discussion will loop for more user interaction
2.) Advice will relate to user discussions and assessment scores
