### ISSUE TITLE
Fix these Issues

### ISSUE THREAD

**Issue by nnguyen682** [nnguyen682/CECS491ATeam4#56]
Add Synonym : Twice
Fix the Test
Add Help for the new users

**Comment by nnguyen682** [comment]
Added the Help message to the new users which will shows all the features. And Tell the return users to say helps to show the features again

**Comment by nnguyen682** [comment]
Alexa will respond correctly when the users answer the questions out side the loops that we have in the Test

**Comment by nnguyen682** [comment]
Adding more synonym to the numbers slot. So that we users won't have to answer numbers only. The answer keys can be often, usually, never , not at all, etc... and the point will be given based on it, to make conversation sounds more natural.

**Comment by jespinoza17** [comment]
Anthony is working on the enhanced discussion feature for the demo today. I will continue to look over the skill states in the code so that we don not run into any bugs.

**Comment by nnguyen682** [comment]
Fixed the number extensions.
At first, If we put number bigger than 3 then it would cause the error with naming intentions. Now we cover all the synonymy and it works perfectly in order. There is still different between or original numbers intentions and others.
